version: 2.1
orbs:
  aws-ecr: circleci/aws-ecr@9.4.0
  aws-cli: circleci/aws-cli@4.2.0

executors:
  docker-executor:
    docker:
      - image: cimg/python:3.12
jobs:
  build:
    executor: docker-executor
    parameters:
      account_id:
        type: string
        default: ""
      oidc_role_arn:
        type: string
        default: ""
      environment:
        type: string
        default: ""
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true
      - aws-ecr/build_and_push_image:
          auth:
            - aws-cli/setup:
                role_arn: << parameters.oidc_role_arn >>  #$AWS_OIDC_ROLE_STRIDEHEALTH_PROD
          account_id: << parameters.account_id >>
          create_repo: false
          extra_build_args: --provenance=false
          push_image: true
          region: <<# if parameters.environment == "dev" >>us-west-1<<# else >>us-west-2<<# endif >>
          repo: "<< parameters.environment >>-security-scan-toolbox-ecr"
          skip_when_tags_exist: false
          tag: $SHORT_SHA, latest

  test:
    executor: docker-executor
    steps:
      - setup_remote_docker
      - run:
          name: Pull Dev Image
          command: |
            aws ecr get-login-password --region $AWS_REGION | docker login --username AWS --password-stdin $DEV_ECR_URL
            docker pull $DEV_ECR_URL/{}}
      - run:
          name: Run Tests
          command: |
            docker run --rm $DEV_ECR_URL/{} dispatcher --help

workflows:
  build-test-deploy:
    jobs:
      - build:
          name: build-dev
          account_id: "025748181824"
          oidc_role_arn: $AWS_OIDC_ROLE_DEV
          environment: "dev"
      - test:
          requires:
            - build-dev
      - approve:
          type: approval
          requires:
            - test
          filters:
            branches:
              only: main
      - build:
          name: build-prod
          account_id: "025748181824"
          oidc_role_arn: $AWS_OIDC_ROLE_PROD
          environment: "prod"
          requires:
            - test
          filters:
            branches:
              only: main
          