version: 2.1
orbs:
  aws-ecr: circleci/aws-ecr@9.4.0
  aws-cli: circleci/aws-cli@4.2.0

executors:
  docker-executor:
    docker:
      - image: cimg/python:3.12
jobs:
  build:
    executor: docker-executor
    parameters:
      account_id:
        type: string
        default: ""
      oidc_role_arn:
        type: string
        default: ""
      env:
        type: string
        default: ""
      region:
        type: string
        default: ""
    steps:
      - checkout
      - run:
          name: Define Environment Variable at Runtime
          command: |
            echo "export SHORT_SHA=$(echo $CIRCLE_SHA1 | head -c 7)" >> "$BASH_ENV"
            source "$BASH_ENV"
      - setup_remote_docker:
          docker_layer_caching: true
      - aws-ecr/build_and_push_image:
          auth:
            - aws-cli/setup:
                role_arn: << parameters.oidc_role_arn >>  #$AWS_OIDC_ROLE_STRIDEHEALTH_PROD
          account_id: << parameters.account_id >>
          create_repo: false
          extra_build_args: --provenance=false
          push_image: true
          build_path: .
          dockerfile: Dockerfile
          repo: "<< parameters.env >>-security-scan-toolbox-ecr"
          region: << parameters.region >>
          skip_when_tags_exist: false
          tag: "$SHORT_SHA,latest"
  test:
    executor: docker-executor
    steps:
      - setup_remote_docker
      - run:
          name: Pull Dev Image
          command: |
            aws ecr get-login-password --region us-west-1 | docker login --username AWS --password-stdin $AWS_ECR_ACCOUNT_DEV_URL
            docker pull $AWS_ECR_ACCOUNT_DEV_URL/dev-security-scan-toolbox-ecr:latest
      - run:
          name: Run Tests
          command: |
            docker run --rm $AWS_ECR_ACCOUNT_DEV_URL/dev-security-scan-toolbox-ecr:latest dispatcher --help

workflows:
  build-test-deploy:
    jobs:
      - build:
          name: build-push-dev
          account_id: "025748181824"
          oidc_role_arn: $AWS_OIDC_ROLE_DEV
          env: dev
          region: us-west-1
      - test:
          requires:
            - build-dev
          context:
            - stride-global
      - approve:
          type: approval
          requires:
            - test
          filters:
            branches:
              only: main
      - build:
          name: build-push-prod
          account_id: "025748181824"
          oidc_role_arn: $AWS_OIDC_ROLE_PROD
          env: "prod"
          region: us-west-2
          requires:
            - approve
          filters:
            branches:
              only: main
          